### ISSUE TITLE
Ревью на Operator page

### ISSUE THREAD

**Issue by krasnikov-andrew** [Kvinto1986/Online-stock-frontend#86]
https://github.com/Kvinto1986/Online-stock-frontend/blob/5eab1666d77c649d4c026fc53259ab30eda67497/src/components/operatorPage/index.jsx#L10-L11
Перенести в StepperPage

**Comment by koorva** [comment]
https://github.com/Kvinto1986/Online-stock-frontend/blob/5eab1666d77c649d4c026fc53259ab30eda67497/src/components/operatorPage/index.jsx#L19
https://github.com/Kvinto1986/Online-stock-frontend/blob/5eab1666d77c649d4c026fc53259ab30eda67497/src/components/operatorPage/index.jsx#L21
Исправить форматирование

**Comment by koorva** [comment]
https://github.com/Kvinto1986/Online-stock-frontend/blob/5eab1666d77c649d4c026fc53259ab30eda67497/src/components/operatorPage/stepperPage.jsx#L35
В JSX элементах используются двойные кавычки. Если твой линтер не подхватил правила, зайди в package.json, вверху должно появиться предложение использовать правила ESLint

**Comment by koorva** [comment]
https://github.com/Kvinto1986/Online-stock-frontend/blob/5eab1666d77c649d4c026fc53259ab30eda67497/src/components/operatorPage/stepperPage.jsx#L20
Эта переменная может и должна быть объявлена за пределами компонента.

**Comment by koorva** [comment]
https://github.com/Kvinto1986/Online-stock-frontend/blob/5eab1666d77c649d4c026fc53259ab30eda67497/src/components/operatorPage/stepperPage.jsx#L25-L27
Эта функция не нужна. Ты можешь сразу записать массив в переменную steps.

**Comment by koorva** [comment]
https://github.com/Kvinto1986/Online-stock-frontend/blob/5eab1666d77c649d4c026fc53259ab30eda67497/src/components/operatorPage/stepperPage.jsx#L22
Этот стрейт используется только внутри компонента ExpansionPanel. Почему бы не объявить его там?

https://github.com/Kvinto1986/Online-stock-frontend/blob/5eab1666d77c649d4c026fc53259ab30eda67497/src/components/operatorPage/stepperPage.jsx#L23
Такая же история

**Comment by koorva** [comment]
https://github.com/Kvinto1986/Online-stock-frontend/blob/5eab1666d77c649d4c026fc53259ab30eda67497/src/components/operatorPage/stepperPage.jsx#L22-L23
Вижу ты создал переиспользуемый компонент и передаёшь в него стейт. Я думаю этот стейт можно вшить в компонент, раз ты его не изменяешь снаружи.

**Comment by koorva** [comment]
https://github.com/Kvinto1986/Online-stock-frontend/blob/5eab1666d77c649d4c026fc53259ab30eda67497/src/components/operatorPage/stepperPage.jsx#L44
Аттрибут болжен начинаться с маленькой буквы.

**Comment by koorva** [comment]
Странно что ты сделал <ExpansionPanel> заточенным только под этот степпер, но не включил в него <Search>

**Comment by koorva** [comment]
https://github.com/Kvinto1986/Online-stock-frontend/blob/5eab1666d77c649d4c026fc53259ab30eda67497/src/components/operatorPage/stepperPage.jsx#L81-L84
Ну это рискованно. А если у тебя степ будет 6? Сообщение будет говорить что всё отлично, но явно произошла ошибка

**Comment by koorva** [comment]
https://github.com/Kvinto1986/Online-stock-frontend/blob/5eab1666d77c649d4c026fc53259ab30eda67497/src/components/operatorPage/expansionPanel.jsx#L10
Ctrl+Alt+L
Ctrl+Alt+O
Жми как можно чаще и такого не будет

**Comment by koorva** [comment]
https://github.com/Kvinto1986/Online-stock-frontend/blob/5eab1666d77c649d4c026fc53259ab30eda67497/src/components/operatorPage/search.jsx#L1
useState не используется

**Comment by koorva** [comment]
https://github.com/Kvinto1986/Online-stock-frontend/blob/5eab1666d77c649d4c026fc53259ab30eda67497/src/components/operatorPage/search.jsx#L10
Ctrl+Alt+L
